# Generated by Django 6.0.7 on 2026-07-15 13:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista'), ('institucion', 'Institucion')], default='minorista', max_length=20)),
                ('nombre', models.CharField(max_length=180)),
                ('nit_ci', models.CharField(blank=True, max_length=40, verbose_name='NIT/CI')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('qr', 'QR'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Credito')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'metodo de pago',
                'verbose_name_plural': 'metodos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('nit', models.CharField(blank=True, max_length=40)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('almacen', 'Almacen'), ('mayorista', 'Mayorista'), ('vendedor', 'Vendedor'), ('caja', 'Caja'), ('administracion', 'Administracion')], default='vendedor', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_retail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de empleado',
                'verbose_name_plural': 'perfiles de empleados',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='SKU')),
                ('codigo_barra', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='retail.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='retail.proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('abierta_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='retail.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesion de caja',
                'verbose_name_plural': 'sesiones de caja',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('canal', models.CharField(choices=[('mostrador', 'Mostrador'), ('mayorista', 'Mayorista')], default='mostrador', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cobradas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='retail.cliente')),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='retail.sesioncaja')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='retail.metodopago')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('sesion_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='retail.sesioncaja')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='retail.venta')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolucion')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='retail.producto')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='retail.venta')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='retail.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='retail.venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='retail_prod_sku_8c75fb_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='retail_prod_nombre_de185d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('caja',), name='una_sesion_abierta_por_caja'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero'], name='retail_vent_numero_629ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='retail_vent_fecha_f1a440_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='retail_vent_estado_96fc24_idx'),
        ),
    ]
